[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
license = "MIT"

[dependencies]
pico-args = "0.4.2"
rayon = "=1.5.1"
crossbeam-deque = "=0.8.1"
crossbeam-epoch = "=0.9.5"
crossbeam-utils = "=0.8.7"
regex = "1.3.9"
rustc_codegen_nvvm = { path = "../crates/rustc_codegen_nvvm" }
